POST http://localhost:3003/api/blog
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVuaXF1ZXVzZXIiLCJpZCI6IjY4NDU4YWU0MGQ0ZTA5ZjE5YTY3YzMzMyIsImlhdCI6MTc0OTQwODY1Mn0.WOG2YwWsodzHbojTAyoVkBwHn9GQWm2gp4VH7Ode-cI
Content-Type: application/json

{
  "title": "Meyzi blog",
  "author": "littley Doey",
  "url": "https://example.com",
  "likes": 10
}
